/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.libsdl2;

public class SDL_HapticDirection {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SDL_HapticDirection(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SDL_HapticDirection obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(SDL_HapticDirection obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        sdl2javaJNI.delete_SDL_HapticDirection(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setType(SWIGTYPE_p_uint8_t value) {
    sdl2javaJNI.SDL_HapticDirection_type_set(swigCPtr, this, SWIGTYPE_p_uint8_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint8_t getType() {
    return new SWIGTYPE_p_uint8_t(sdl2javaJNI.SDL_HapticDirection_type_get(swigCPtr, this), true);
  }

  public void setDir(SWIGTYPE_p_int32_t value) {
    sdl2javaJNI.SDL_HapticDirection_dir_set(swigCPtr, this, SWIGTYPE_p_int32_t.getCPtr(value));
  }

  public SWIGTYPE_p_int32_t getDir() {
    long cPtr = sdl2javaJNI.SDL_HapticDirection_dir_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int32_t(cPtr, false);
  }

  public SDL_HapticDirection() {
    this(sdl2javaJNI.new_SDL_HapticDirection(), true);
  }

}
