/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.libsdl2;

public class SDL_MessageBoxColor {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SDL_MessageBoxColor(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SDL_MessageBoxColor obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(SDL_MessageBoxColor obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        sdl2javaJNI.delete_SDL_MessageBoxColor(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setR(SWIGTYPE_p_uint8_t value) {
    sdl2javaJNI.SDL_MessageBoxColor_r_set(swigCPtr, this, SWIGTYPE_p_uint8_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint8_t getR() {
    return new SWIGTYPE_p_uint8_t(sdl2javaJNI.SDL_MessageBoxColor_r_get(swigCPtr, this), true);
  }

  public void setG(SWIGTYPE_p_uint8_t value) {
    sdl2javaJNI.SDL_MessageBoxColor_g_set(swigCPtr, this, SWIGTYPE_p_uint8_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint8_t getG() {
    return new SWIGTYPE_p_uint8_t(sdl2javaJNI.SDL_MessageBoxColor_g_get(swigCPtr, this), true);
  }

  public void setB(SWIGTYPE_p_uint8_t value) {
    sdl2javaJNI.SDL_MessageBoxColor_b_set(swigCPtr, this, SWIGTYPE_p_uint8_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint8_t getB() {
    return new SWIGTYPE_p_uint8_t(sdl2javaJNI.SDL_MessageBoxColor_b_get(swigCPtr, this), true);
  }

  public SDL_MessageBoxColor() {
    this(sdl2javaJNI.new_SDL_MessageBoxColor(), true);
  }

}
