/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.libsdl2;

public class SDL_AudioCVT {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SDL_AudioCVT(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SDL_AudioCVT obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(SDL_AudioCVT obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        sdl2javaJNI.delete_SDL_AudioCVT(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setNeeded(int value) {
    sdl2javaJNI.SDL_AudioCVT_needed_set(swigCPtr, this, value);
  }

  public int getNeeded() {
    return sdl2javaJNI.SDL_AudioCVT_needed_get(swigCPtr, this);
  }

  public void setSrc_format(SWIGTYPE_p_uint16_t value) {
    sdl2javaJNI.SDL_AudioCVT_src_format_set(swigCPtr, this, SWIGTYPE_p_uint16_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint16_t getSrc_format() {
    return new SWIGTYPE_p_uint16_t(sdl2javaJNI.SDL_AudioCVT_src_format_get(swigCPtr, this), true);
  }

  public void setDst_format(SWIGTYPE_p_uint16_t value) {
    sdl2javaJNI.SDL_AudioCVT_dst_format_set(swigCPtr, this, SWIGTYPE_p_uint16_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint16_t getDst_format() {
    return new SWIGTYPE_p_uint16_t(sdl2javaJNI.SDL_AudioCVT_dst_format_get(swigCPtr, this), true);
  }

  public void setRate_incr(double value) {
    sdl2javaJNI.SDL_AudioCVT_rate_incr_set(swigCPtr, this, value);
  }

  public double getRate_incr() {
    return sdl2javaJNI.SDL_AudioCVT_rate_incr_get(swigCPtr, this);
  }

  public void setBuf(SWIGTYPE_p_uint8_t value) {
    sdl2javaJNI.SDL_AudioCVT_buf_set(swigCPtr, this, SWIGTYPE_p_uint8_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint8_t getBuf() {
    long cPtr = sdl2javaJNI.SDL_AudioCVT_buf_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_uint8_t(cPtr, false);
  }

  public void setLen(int value) {
    sdl2javaJNI.SDL_AudioCVT_len_set(swigCPtr, this, value);
  }

  public int getLen() {
    return sdl2javaJNI.SDL_AudioCVT_len_get(swigCPtr, this);
  }

  public void setLen_cvt(int value) {
    sdl2javaJNI.SDL_AudioCVT_len_cvt_set(swigCPtr, this, value);
  }

  public int getLen_cvt() {
    return sdl2javaJNI.SDL_AudioCVT_len_cvt_get(swigCPtr, this);
  }

  public void setLen_mult(int value) {
    sdl2javaJNI.SDL_AudioCVT_len_mult_set(swigCPtr, this, value);
  }

  public int getLen_mult() {
    return sdl2javaJNI.SDL_AudioCVT_len_mult_get(swigCPtr, this);
  }

  public void setLen_ratio(double value) {
    sdl2javaJNI.SDL_AudioCVT_len_ratio_set(swigCPtr, this, value);
  }

  public double getLen_ratio() {
    return sdl2javaJNI.SDL_AudioCVT_len_ratio_get(swigCPtr, this);
  }

  public void setFilters(SWIGTYPE_p_p_f_p_struct_SDL_AudioCVT_uint16_t__void value) {
    sdl2javaJNI.SDL_AudioCVT_filters_set(swigCPtr, this, SWIGTYPE_p_p_f_p_struct_SDL_AudioCVT_uint16_t__void.getCPtr(value));
  }

  public SWIGTYPE_p_p_f_p_struct_SDL_AudioCVT_uint16_t__void getFilters() {
    long cPtr = sdl2javaJNI.SDL_AudioCVT_filters_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_f_p_struct_SDL_AudioCVT_uint16_t__void(cPtr, false);
  }

  public void setFilter_index(int value) {
    sdl2javaJNI.SDL_AudioCVT_filter_index_set(swigCPtr, this, value);
  }

  public int getFilter_index() {
    return sdl2javaJNI.SDL_AudioCVT_filter_index_get(swigCPtr, this);
  }

  public SDL_AudioCVT() {
    this(sdl2javaJNI.new_SDL_AudioCVT(), true);
  }

}
