/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.libsdl2;

public class SDL_MessageBoxButtonData {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SDL_MessageBoxButtonData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SDL_MessageBoxButtonData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(SDL_MessageBoxButtonData obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        sdl2javaJNI.delete_SDL_MessageBoxButtonData(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setFlags(SWIGTYPE_p_uint32_t value) {
    sdl2javaJNI.SDL_MessageBoxButtonData_flags_set(swigCPtr, this, SWIGTYPE_p_uint32_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint32_t getFlags() {
    return new SWIGTYPE_p_uint32_t(sdl2javaJNI.SDL_MessageBoxButtonData_flags_get(swigCPtr, this), true);
  }

  public void setButtonid(int value) {
    sdl2javaJNI.SDL_MessageBoxButtonData_buttonid_set(swigCPtr, this, value);
  }

  public int getButtonid() {
    return sdl2javaJNI.SDL_MessageBoxButtonData_buttonid_get(swigCPtr, this);
  }

  public void setText(String value) {
    sdl2javaJNI.SDL_MessageBoxButtonData_text_set(swigCPtr, this, value);
  }

  public String getText() {
    return sdl2javaJNI.SDL_MessageBoxButtonData_text_get(swigCPtr, this);
  }

  public SDL_MessageBoxButtonData() {
    this(sdl2javaJNI.new_SDL_MessageBoxButtonData(), true);
  }

}
