/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.libsdl2;

public class SDL_HapticLeftRight {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SDL_HapticLeftRight(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SDL_HapticLeftRight obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(SDL_HapticLeftRight obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        sdl2javaJNI.delete_SDL_HapticLeftRight(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setType(SWIGTYPE_p_uint16_t value) {
    sdl2javaJNI.SDL_HapticLeftRight_type_set(swigCPtr, this, SWIGTYPE_p_uint16_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint16_t getType() {
    return new SWIGTYPE_p_uint16_t(sdl2javaJNI.SDL_HapticLeftRight_type_get(swigCPtr, this), true);
  }

  public void setLength(SWIGTYPE_p_uint32_t value) {
    sdl2javaJNI.SDL_HapticLeftRight_length_set(swigCPtr, this, SWIGTYPE_p_uint32_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint32_t getLength() {
    return new SWIGTYPE_p_uint32_t(sdl2javaJNI.SDL_HapticLeftRight_length_get(swigCPtr, this), true);
  }

  public void setLarge_magnitude(SWIGTYPE_p_uint16_t value) {
    sdl2javaJNI.SDL_HapticLeftRight_large_magnitude_set(swigCPtr, this, SWIGTYPE_p_uint16_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint16_t getLarge_magnitude() {
    return new SWIGTYPE_p_uint16_t(sdl2javaJNI.SDL_HapticLeftRight_large_magnitude_get(swigCPtr, this), true);
  }

  public void setSmall_magnitude(SWIGTYPE_p_uint16_t value) {
    sdl2javaJNI.SDL_HapticLeftRight_small_magnitude_set(swigCPtr, this, SWIGTYPE_p_uint16_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint16_t getSmall_magnitude() {
    return new SWIGTYPE_p_uint16_t(sdl2javaJNI.SDL_HapticLeftRight_small_magnitude_get(swigCPtr, this), true);
  }

  public SDL_HapticLeftRight() {
    this(sdl2javaJNI.new_SDL_HapticLeftRight(), true);
  }

}
