/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.libsdl2;

public final class SDL_FlashOperation {
  public final static SDL_FlashOperation SDL_FLASH_CANCEL = new SDL_FlashOperation("SDL_FLASH_CANCEL");
  public final static SDL_FlashOperation SDL_FLASH_BRIEFLY = new SDL_FlashOperation("SDL_FLASH_BRIEFLY");
  public final static SDL_FlashOperation SDL_FLASH_UNTIL_FOCUSED = new SDL_FlashOperation("SDL_FLASH_UNTIL_FOCUSED");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SDL_FlashOperation swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + SDL_FlashOperation.class + " with value " + swigValue);
  }

  private SDL_FlashOperation(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SDL_FlashOperation(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SDL_FlashOperation(String swigName, SDL_FlashOperation swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SDL_FlashOperation[] swigValues = { SDL_FLASH_CANCEL, SDL_FLASH_BRIEFLY, SDL_FLASH_UNTIL_FOCUSED };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

