/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.libsdl2;

public class SDL_MouseMotionEvent {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SDL_MouseMotionEvent(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SDL_MouseMotionEvent obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(SDL_MouseMotionEvent obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        sdl2javaJNI.delete_SDL_MouseMotionEvent(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setType(SWIGTYPE_p_uint32_t value) {
    sdl2javaJNI.SDL_MouseMotionEvent_type_set(swigCPtr, this, SWIGTYPE_p_uint32_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint32_t getType() {
    return new SWIGTYPE_p_uint32_t(sdl2javaJNI.SDL_MouseMotionEvent_type_get(swigCPtr, this), true);
  }

  public void setTimestamp(SWIGTYPE_p_uint32_t value) {
    sdl2javaJNI.SDL_MouseMotionEvent_timestamp_set(swigCPtr, this, SWIGTYPE_p_uint32_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint32_t getTimestamp() {
    return new SWIGTYPE_p_uint32_t(sdl2javaJNI.SDL_MouseMotionEvent_timestamp_get(swigCPtr, this), true);
  }

  public void setWindowID(SWIGTYPE_p_uint32_t value) {
    sdl2javaJNI.SDL_MouseMotionEvent_windowID_set(swigCPtr, this, SWIGTYPE_p_uint32_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint32_t getWindowID() {
    return new SWIGTYPE_p_uint32_t(sdl2javaJNI.SDL_MouseMotionEvent_windowID_get(swigCPtr, this), true);
  }

  public void setWhich(SWIGTYPE_p_uint32_t value) {
    sdl2javaJNI.SDL_MouseMotionEvent_which_set(swigCPtr, this, SWIGTYPE_p_uint32_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint32_t getWhich() {
    return new SWIGTYPE_p_uint32_t(sdl2javaJNI.SDL_MouseMotionEvent_which_get(swigCPtr, this), true);
  }

  public void setState(SWIGTYPE_p_uint32_t value) {
    sdl2javaJNI.SDL_MouseMotionEvent_state_set(swigCPtr, this, SWIGTYPE_p_uint32_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint32_t getState() {
    return new SWIGTYPE_p_uint32_t(sdl2javaJNI.SDL_MouseMotionEvent_state_get(swigCPtr, this), true);
  }

  public void setX(SWIGTYPE_p_int32_t value) {
    sdl2javaJNI.SDL_MouseMotionEvent_x_set(swigCPtr, this, SWIGTYPE_p_int32_t.getCPtr(value));
  }

  public SWIGTYPE_p_int32_t getX() {
    return new SWIGTYPE_p_int32_t(sdl2javaJNI.SDL_MouseMotionEvent_x_get(swigCPtr, this), true);
  }

  public void setY(SWIGTYPE_p_int32_t value) {
    sdl2javaJNI.SDL_MouseMotionEvent_y_set(swigCPtr, this, SWIGTYPE_p_int32_t.getCPtr(value));
  }

  public SWIGTYPE_p_int32_t getY() {
    return new SWIGTYPE_p_int32_t(sdl2javaJNI.SDL_MouseMotionEvent_y_get(swigCPtr, this), true);
  }

  public void setXrel(SWIGTYPE_p_int32_t value) {
    sdl2javaJNI.SDL_MouseMotionEvent_xrel_set(swigCPtr, this, SWIGTYPE_p_int32_t.getCPtr(value));
  }

  public SWIGTYPE_p_int32_t getXrel() {
    return new SWIGTYPE_p_int32_t(sdl2javaJNI.SDL_MouseMotionEvent_xrel_get(swigCPtr, this), true);
  }

  public void setYrel(SWIGTYPE_p_int32_t value) {
    sdl2javaJNI.SDL_MouseMotionEvent_yrel_set(swigCPtr, this, SWIGTYPE_p_int32_t.getCPtr(value));
  }

  public SWIGTYPE_p_int32_t getYrel() {
    return new SWIGTYPE_p_int32_t(sdl2javaJNI.SDL_MouseMotionEvent_yrel_get(swigCPtr, this), true);
  }

  public SDL_MouseMotionEvent() {
    this(sdl2javaJNI.new_SDL_MouseMotionEvent(), true);
  }

}
