/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.libsdl2;

public final class SDL_ScaleMode {
  public final static SDL_ScaleMode SDL_ScaleModeNearest = new SDL_ScaleMode("SDL_ScaleModeNearest");
  public final static SDL_ScaleMode SDL_ScaleModeLinear = new SDL_ScaleMode("SDL_ScaleModeLinear");
  public final static SDL_ScaleMode SDL_ScaleModeBest = new SDL_ScaleMode("SDL_ScaleModeBest");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SDL_ScaleMode swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + SDL_ScaleMode.class + " with value " + swigValue);
  }

  private SDL_ScaleMode(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SDL_ScaleMode(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SDL_ScaleMode(String swigName, SDL_ScaleMode swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SDL_ScaleMode[] swigValues = { SDL_ScaleModeNearest, SDL_ScaleModeLinear, SDL_ScaleModeBest };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

