/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.libsdl2;

public class SDL_version {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SDL_version(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SDL_version obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(SDL_version obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        sdl2javaJNI.delete_SDL_version(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMajor(SWIGTYPE_p_uint8_t value) {
    sdl2javaJNI.SDL_version_major_set(swigCPtr, this, SWIGTYPE_p_uint8_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint8_t getMajor() {
    return new SWIGTYPE_p_uint8_t(sdl2javaJNI.SDL_version_major_get(swigCPtr, this), true);
  }

  public void setMinor(SWIGTYPE_p_uint8_t value) {
    sdl2javaJNI.SDL_version_minor_set(swigCPtr, this, SWIGTYPE_p_uint8_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint8_t getMinor() {
    return new SWIGTYPE_p_uint8_t(sdl2javaJNI.SDL_version_minor_get(swigCPtr, this), true);
  }

  public void setPatch(SWIGTYPE_p_uint8_t value) {
    sdl2javaJNI.SDL_version_patch_set(swigCPtr, this, SWIGTYPE_p_uint8_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint8_t getPatch() {
    return new SWIGTYPE_p_uint8_t(sdl2javaJNI.SDL_version_patch_get(swigCPtr, this), true);
  }

  public SDL_version() {
    this(sdl2javaJNI.new_SDL_version(), true);
  }

}
