/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.libsdl2;

public class SDL_HapticCondition {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SDL_HapticCondition(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SDL_HapticCondition obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(SDL_HapticCondition obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        sdl2javaJNI.delete_SDL_HapticCondition(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setType(SWIGTYPE_p_uint16_t value) {
    sdl2javaJNI.SDL_HapticCondition_type_set(swigCPtr, this, SWIGTYPE_p_uint16_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint16_t getType() {
    return new SWIGTYPE_p_uint16_t(sdl2javaJNI.SDL_HapticCondition_type_get(swigCPtr, this), true);
  }

  public void setDirection(SDL_HapticDirection value) {
    sdl2javaJNI.SDL_HapticCondition_direction_set(swigCPtr, this, SDL_HapticDirection.getCPtr(value), value);
  }

  public SDL_HapticDirection getDirection() {
    long cPtr = sdl2javaJNI.SDL_HapticCondition_direction_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SDL_HapticDirection(cPtr, false);
  }

  public void setLength(SWIGTYPE_p_uint32_t value) {
    sdl2javaJNI.SDL_HapticCondition_length_set(swigCPtr, this, SWIGTYPE_p_uint32_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint32_t getLength() {
    return new SWIGTYPE_p_uint32_t(sdl2javaJNI.SDL_HapticCondition_length_get(swigCPtr, this), true);
  }

  public void setDelay(SWIGTYPE_p_uint16_t value) {
    sdl2javaJNI.SDL_HapticCondition_delay_set(swigCPtr, this, SWIGTYPE_p_uint16_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint16_t getDelay() {
    return new SWIGTYPE_p_uint16_t(sdl2javaJNI.SDL_HapticCondition_delay_get(swigCPtr, this), true);
  }

  public void setButton(SWIGTYPE_p_uint16_t value) {
    sdl2javaJNI.SDL_HapticCondition_button_set(swigCPtr, this, SWIGTYPE_p_uint16_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint16_t getButton() {
    return new SWIGTYPE_p_uint16_t(sdl2javaJNI.SDL_HapticCondition_button_get(swigCPtr, this), true);
  }

  public void setInterval(SWIGTYPE_p_uint16_t value) {
    sdl2javaJNI.SDL_HapticCondition_interval_set(swigCPtr, this, SWIGTYPE_p_uint16_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint16_t getInterval() {
    return new SWIGTYPE_p_uint16_t(sdl2javaJNI.SDL_HapticCondition_interval_get(swigCPtr, this), true);
  }

  public void setRight_sat(SWIGTYPE_p_uint16_t value) {
    sdl2javaJNI.SDL_HapticCondition_right_sat_set(swigCPtr, this, SWIGTYPE_p_uint16_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint16_t getRight_sat() {
    long cPtr = sdl2javaJNI.SDL_HapticCondition_right_sat_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_uint16_t(cPtr, false);
  }

  public void setLeft_sat(SWIGTYPE_p_uint16_t value) {
    sdl2javaJNI.SDL_HapticCondition_left_sat_set(swigCPtr, this, SWIGTYPE_p_uint16_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint16_t getLeft_sat() {
    long cPtr = sdl2javaJNI.SDL_HapticCondition_left_sat_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_uint16_t(cPtr, false);
  }

  public void setRight_coeff(SWIGTYPE_p_int16_t value) {
    sdl2javaJNI.SDL_HapticCondition_right_coeff_set(swigCPtr, this, SWIGTYPE_p_int16_t.getCPtr(value));
  }

  public SWIGTYPE_p_int16_t getRight_coeff() {
    long cPtr = sdl2javaJNI.SDL_HapticCondition_right_coeff_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int16_t(cPtr, false);
  }

  public void setLeft_coeff(SWIGTYPE_p_int16_t value) {
    sdl2javaJNI.SDL_HapticCondition_left_coeff_set(swigCPtr, this, SWIGTYPE_p_int16_t.getCPtr(value));
  }

  public SWIGTYPE_p_int16_t getLeft_coeff() {
    long cPtr = sdl2javaJNI.SDL_HapticCondition_left_coeff_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int16_t(cPtr, false);
  }

  public void setDeadband(SWIGTYPE_p_uint16_t value) {
    sdl2javaJNI.SDL_HapticCondition_deadband_set(swigCPtr, this, SWIGTYPE_p_uint16_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint16_t getDeadband() {
    long cPtr = sdl2javaJNI.SDL_HapticCondition_deadband_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_uint16_t(cPtr, false);
  }

  public void setCenter(SWIGTYPE_p_int16_t value) {
    sdl2javaJNI.SDL_HapticCondition_center_set(swigCPtr, this, SWIGTYPE_p_int16_t.getCPtr(value));
  }

  public SWIGTYPE_p_int16_t getCenter() {
    long cPtr = sdl2javaJNI.SDL_HapticCondition_center_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int16_t(cPtr, false);
  }

  public SDL_HapticCondition() {
    this(sdl2javaJNI.new_SDL_HapticCondition(), true);
  }

}
