/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.libsdl2;

public final class SDL_JoystickType {
  public final static SDL_JoystickType SDL_JOYSTICK_TYPE_UNKNOWN = new SDL_JoystickType("SDL_JOYSTICK_TYPE_UNKNOWN");
  public final static SDL_JoystickType SDL_JOYSTICK_TYPE_GAMECONTROLLER = new SDL_JoystickType("SDL_JOYSTICK_TYPE_GAMECONTROLLER");
  public final static SDL_JoystickType SDL_JOYSTICK_TYPE_WHEEL = new SDL_JoystickType("SDL_JOYSTICK_TYPE_WHEEL");
  public final static SDL_JoystickType SDL_JOYSTICK_TYPE_ARCADE_STICK = new SDL_JoystickType("SDL_JOYSTICK_TYPE_ARCADE_STICK");
  public final static SDL_JoystickType SDL_JOYSTICK_TYPE_FLIGHT_STICK = new SDL_JoystickType("SDL_JOYSTICK_TYPE_FLIGHT_STICK");
  public final static SDL_JoystickType SDL_JOYSTICK_TYPE_DANCE_PAD = new SDL_JoystickType("SDL_JOYSTICK_TYPE_DANCE_PAD");
  public final static SDL_JoystickType SDL_JOYSTICK_TYPE_GUITAR = new SDL_JoystickType("SDL_JOYSTICK_TYPE_GUITAR");
  public final static SDL_JoystickType SDL_JOYSTICK_TYPE_DRUM_KIT = new SDL_JoystickType("SDL_JOYSTICK_TYPE_DRUM_KIT");
  public final static SDL_JoystickType SDL_JOYSTICK_TYPE_ARCADE_PAD = new SDL_JoystickType("SDL_JOYSTICK_TYPE_ARCADE_PAD");
  public final static SDL_JoystickType SDL_JOYSTICK_TYPE_THROTTLE = new SDL_JoystickType("SDL_JOYSTICK_TYPE_THROTTLE");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SDL_JoystickType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + SDL_JoystickType.class + " with value " + swigValue);
  }

  private SDL_JoystickType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SDL_JoystickType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SDL_JoystickType(String swigName, SDL_JoystickType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SDL_JoystickType[] swigValues = { SDL_JOYSTICK_TYPE_UNKNOWN, SDL_JOYSTICK_TYPE_GAMECONTROLLER, SDL_JOYSTICK_TYPE_WHEEL, SDL_JOYSTICK_TYPE_ARCADE_STICK, SDL_JOYSTICK_TYPE_FLIGHT_STICK, SDL_JOYSTICK_TYPE_DANCE_PAD, SDL_JOYSTICK_TYPE_GUITAR, SDL_JOYSTICK_TYPE_DRUM_KIT, SDL_JOYSTICK_TYPE_ARCADE_PAD, SDL_JOYSTICK_TYPE_THROTTLE };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

