/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.libsdl2;

public class SDL_MultiGestureEvent {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SDL_MultiGestureEvent(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SDL_MultiGestureEvent obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(SDL_MultiGestureEvent obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        sdl2javaJNI.delete_SDL_MultiGestureEvent(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setType(SWIGTYPE_p_uint32_t value) {
    sdl2javaJNI.SDL_MultiGestureEvent_type_set(swigCPtr, this, SWIGTYPE_p_uint32_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint32_t getType() {
    return new SWIGTYPE_p_uint32_t(sdl2javaJNI.SDL_MultiGestureEvent_type_get(swigCPtr, this), true);
  }

  public void setTimestamp(SWIGTYPE_p_uint32_t value) {
    sdl2javaJNI.SDL_MultiGestureEvent_timestamp_set(swigCPtr, this, SWIGTYPE_p_uint32_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint32_t getTimestamp() {
    return new SWIGTYPE_p_uint32_t(sdl2javaJNI.SDL_MultiGestureEvent_timestamp_get(swigCPtr, this), true);
  }

  public void setTouchId(SWIGTYPE_p_SDL_TouchID value) {
    sdl2javaJNI.SDL_MultiGestureEvent_touchId_set(swigCPtr, this, SWIGTYPE_p_SDL_TouchID.getCPtr(value));
  }

  public SWIGTYPE_p_SDL_TouchID getTouchId() {
    return new SWIGTYPE_p_SDL_TouchID(sdl2javaJNI.SDL_MultiGestureEvent_touchId_get(swigCPtr, this), true);
  }

  public void setDTheta(float value) {
    sdl2javaJNI.SDL_MultiGestureEvent_dTheta_set(swigCPtr, this, value);
  }

  public float getDTheta() {
    return sdl2javaJNI.SDL_MultiGestureEvent_dTheta_get(swigCPtr, this);
  }

  public void setDDist(float value) {
    sdl2javaJNI.SDL_MultiGestureEvent_dDist_set(swigCPtr, this, value);
  }

  public float getDDist() {
    return sdl2javaJNI.SDL_MultiGestureEvent_dDist_get(swigCPtr, this);
  }

  public void setX(float value) {
    sdl2javaJNI.SDL_MultiGestureEvent_x_set(swigCPtr, this, value);
  }

  public float getX() {
    return sdl2javaJNI.SDL_MultiGestureEvent_x_get(swigCPtr, this);
  }

  public void setY(float value) {
    sdl2javaJNI.SDL_MultiGestureEvent_y_set(swigCPtr, this, value);
  }

  public float getY() {
    return sdl2javaJNI.SDL_MultiGestureEvent_y_get(swigCPtr, this);
  }

  public void setNumFingers(SWIGTYPE_p_uint16_t value) {
    sdl2javaJNI.SDL_MultiGestureEvent_numFingers_set(swigCPtr, this, SWIGTYPE_p_uint16_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint16_t getNumFingers() {
    return new SWIGTYPE_p_uint16_t(sdl2javaJNI.SDL_MultiGestureEvent_numFingers_get(swigCPtr, this), true);
  }

  public void setPadding(SWIGTYPE_p_uint16_t value) {
    sdl2javaJNI.SDL_MultiGestureEvent_padding_set(swigCPtr, this, SWIGTYPE_p_uint16_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint16_t getPadding() {
    return new SWIGTYPE_p_uint16_t(sdl2javaJNI.SDL_MultiGestureEvent_padding_get(swigCPtr, this), true);
  }

  public SDL_MultiGestureEvent() {
    this(sdl2javaJNI.new_SDL_MultiGestureEvent(), true);
  }

}
