/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.libsdl2;

public class SDL_DisplayEvent {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SDL_DisplayEvent(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SDL_DisplayEvent obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(SDL_DisplayEvent obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        sdl2javaJNI.delete_SDL_DisplayEvent(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setType(SWIGTYPE_p_uint32_t value) {
    sdl2javaJNI.SDL_DisplayEvent_type_set(swigCPtr, this, SWIGTYPE_p_uint32_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint32_t getType() {
    return new SWIGTYPE_p_uint32_t(sdl2javaJNI.SDL_DisplayEvent_type_get(swigCPtr, this), true);
  }

  public void setTimestamp(SWIGTYPE_p_uint32_t value) {
    sdl2javaJNI.SDL_DisplayEvent_timestamp_set(swigCPtr, this, SWIGTYPE_p_uint32_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint32_t getTimestamp() {
    return new SWIGTYPE_p_uint32_t(sdl2javaJNI.SDL_DisplayEvent_timestamp_get(swigCPtr, this), true);
  }

  public void setDisplay(SWIGTYPE_p_uint32_t value) {
    sdl2javaJNI.SDL_DisplayEvent_display_set(swigCPtr, this, SWIGTYPE_p_uint32_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint32_t getDisplay() {
    return new SWIGTYPE_p_uint32_t(sdl2javaJNI.SDL_DisplayEvent_display_get(swigCPtr, this), true);
  }

  public void setEvent(SWIGTYPE_p_uint8_t value) {
    sdl2javaJNI.SDL_DisplayEvent_event_set(swigCPtr, this, SWIGTYPE_p_uint8_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint8_t getEvent() {
    return new SWIGTYPE_p_uint8_t(sdl2javaJNI.SDL_DisplayEvent_event_get(swigCPtr, this), true);
  }

  public void setPadding1(SWIGTYPE_p_uint8_t value) {
    sdl2javaJNI.SDL_DisplayEvent_padding1_set(swigCPtr, this, SWIGTYPE_p_uint8_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint8_t getPadding1() {
    return new SWIGTYPE_p_uint8_t(sdl2javaJNI.SDL_DisplayEvent_padding1_get(swigCPtr, this), true);
  }

  public void setPadding2(SWIGTYPE_p_uint8_t value) {
    sdl2javaJNI.SDL_DisplayEvent_padding2_set(swigCPtr, this, SWIGTYPE_p_uint8_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint8_t getPadding2() {
    return new SWIGTYPE_p_uint8_t(sdl2javaJNI.SDL_DisplayEvent_padding2_get(swigCPtr, this), true);
  }

  public void setPadding3(SWIGTYPE_p_uint8_t value) {
    sdl2javaJNI.SDL_DisplayEvent_padding3_set(swigCPtr, this, SWIGTYPE_p_uint8_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint8_t getPadding3() {
    return new SWIGTYPE_p_uint8_t(sdl2javaJNI.SDL_DisplayEvent_padding3_get(swigCPtr, this), true);
  }

  public void setData1(SWIGTYPE_p_int32_t value) {
    sdl2javaJNI.SDL_DisplayEvent_data1_set(swigCPtr, this, SWIGTYPE_p_int32_t.getCPtr(value));
  }

  public SWIGTYPE_p_int32_t getData1() {
    return new SWIGTYPE_p_int32_t(sdl2javaJNI.SDL_DisplayEvent_data1_get(swigCPtr, this), true);
  }

  public SDL_DisplayEvent() {
    this(sdl2javaJNI.new_SDL_DisplayEvent(), true);
  }

}
