/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.libsdl2;

public class SDL_AudioSpec {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SDL_AudioSpec(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SDL_AudioSpec obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(SDL_AudioSpec obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        sdl2javaJNI.delete_SDL_AudioSpec(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setFreq(int value) {
    sdl2javaJNI.SDL_AudioSpec_freq_set(swigCPtr, this, value);
  }

  public int getFreq() {
    return sdl2javaJNI.SDL_AudioSpec_freq_get(swigCPtr, this);
  }

  public void setFormat(SWIGTYPE_p_uint16_t value) {
    sdl2javaJNI.SDL_AudioSpec_format_set(swigCPtr, this, SWIGTYPE_p_uint16_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint16_t getFormat() {
    return new SWIGTYPE_p_uint16_t(sdl2javaJNI.SDL_AudioSpec_format_get(swigCPtr, this), true);
  }

  public void setChannels(SWIGTYPE_p_uint8_t value) {
    sdl2javaJNI.SDL_AudioSpec_channels_set(swigCPtr, this, SWIGTYPE_p_uint8_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint8_t getChannels() {
    return new SWIGTYPE_p_uint8_t(sdl2javaJNI.SDL_AudioSpec_channels_get(swigCPtr, this), true);
  }

  public void setSilence(SWIGTYPE_p_uint8_t value) {
    sdl2javaJNI.SDL_AudioSpec_silence_set(swigCPtr, this, SWIGTYPE_p_uint8_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint8_t getSilence() {
    return new SWIGTYPE_p_uint8_t(sdl2javaJNI.SDL_AudioSpec_silence_get(swigCPtr, this), true);
  }

  public void setSamples(SWIGTYPE_p_uint16_t value) {
    sdl2javaJNI.SDL_AudioSpec_samples_set(swigCPtr, this, SWIGTYPE_p_uint16_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint16_t getSamples() {
    return new SWIGTYPE_p_uint16_t(sdl2javaJNI.SDL_AudioSpec_samples_get(swigCPtr, this), true);
  }

  public void setPadding(SWIGTYPE_p_uint16_t value) {
    sdl2javaJNI.SDL_AudioSpec_padding_set(swigCPtr, this, SWIGTYPE_p_uint16_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint16_t getPadding() {
    return new SWIGTYPE_p_uint16_t(sdl2javaJNI.SDL_AudioSpec_padding_get(swigCPtr, this), true);
  }

  public void setSize(SWIGTYPE_p_uint32_t value) {
    sdl2javaJNI.SDL_AudioSpec_size_set(swigCPtr, this, SWIGTYPE_p_uint32_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint32_t getSize() {
    return new SWIGTYPE_p_uint32_t(sdl2javaJNI.SDL_AudioSpec_size_get(swigCPtr, this), true);
  }

  public void setCallback(SWIGTYPE_p_f_p_void_p_uint8_t_int__void value) {
    sdl2javaJNI.SDL_AudioSpec_callback_set(swigCPtr, this, SWIGTYPE_p_f_p_void_p_uint8_t_int__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_void_p_uint8_t_int__void getCallback() {
    long cPtr = sdl2javaJNI.SDL_AudioSpec_callback_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_void_p_uint8_t_int__void(cPtr, false);
  }

  public void setUserdata(SWIGTYPE_p_void value) {
    sdl2javaJNI.SDL_AudioSpec_userdata_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getUserdata() {
    long cPtr = sdl2javaJNI.SDL_AudioSpec_userdata_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public SDL_AudioSpec() {
    this(sdl2javaJNI.new_SDL_AudioSpec(), true);
  }

}
