/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.libsdl2;

public class SDL_TextEditingExtEvent {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SDL_TextEditingExtEvent(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SDL_TextEditingExtEvent obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(SDL_TextEditingExtEvent obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        sdl2javaJNI.delete_SDL_TextEditingExtEvent(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setType(SWIGTYPE_p_uint32_t value) {
    sdl2javaJNI.SDL_TextEditingExtEvent_type_set(swigCPtr, this, SWIGTYPE_p_uint32_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint32_t getType() {
    return new SWIGTYPE_p_uint32_t(sdl2javaJNI.SDL_TextEditingExtEvent_type_get(swigCPtr, this), true);
  }

  public void setTimestamp(SWIGTYPE_p_uint32_t value) {
    sdl2javaJNI.SDL_TextEditingExtEvent_timestamp_set(swigCPtr, this, SWIGTYPE_p_uint32_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint32_t getTimestamp() {
    return new SWIGTYPE_p_uint32_t(sdl2javaJNI.SDL_TextEditingExtEvent_timestamp_get(swigCPtr, this), true);
  }

  public void setWindowID(SWIGTYPE_p_uint32_t value) {
    sdl2javaJNI.SDL_TextEditingExtEvent_windowID_set(swigCPtr, this, SWIGTYPE_p_uint32_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint32_t getWindowID() {
    return new SWIGTYPE_p_uint32_t(sdl2javaJNI.SDL_TextEditingExtEvent_windowID_get(swigCPtr, this), true);
  }

  public void setText(String value) {
    sdl2javaJNI.SDL_TextEditingExtEvent_text_set(swigCPtr, this, value);
  }

  public String getText() {
    return sdl2javaJNI.SDL_TextEditingExtEvent_text_get(swigCPtr, this);
  }

  public void setStart(SWIGTYPE_p_int32_t value) {
    sdl2javaJNI.SDL_TextEditingExtEvent_start_set(swigCPtr, this, SWIGTYPE_p_int32_t.getCPtr(value));
  }

  public SWIGTYPE_p_int32_t getStart() {
    return new SWIGTYPE_p_int32_t(sdl2javaJNI.SDL_TextEditingExtEvent_start_get(swigCPtr, this), true);
  }

  public void setLength(SWIGTYPE_p_int32_t value) {
    sdl2javaJNI.SDL_TextEditingExtEvent_length_set(swigCPtr, this, SWIGTYPE_p_int32_t.getCPtr(value));
  }

  public SWIGTYPE_p_int32_t getLength() {
    return new SWIGTYPE_p_int32_t(sdl2javaJNI.SDL_TextEditingExtEvent_length_get(swigCPtr, this), true);
  }

  public SDL_TextEditingExtEvent() {
    this(sdl2javaJNI.new_SDL_TextEditingExtEvent(), true);
  }

}
