/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.libsdl2;

public class SDL_MessageBoxData {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SDL_MessageBoxData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SDL_MessageBoxData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(SDL_MessageBoxData obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        sdl2javaJNI.delete_SDL_MessageBoxData(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setFlags(SWIGTYPE_p_uint32_t value) {
    sdl2javaJNI.SDL_MessageBoxData_flags_set(swigCPtr, this, SWIGTYPE_p_uint32_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint32_t getFlags() {
    return new SWIGTYPE_p_uint32_t(sdl2javaJNI.SDL_MessageBoxData_flags_get(swigCPtr, this), true);
  }

  public void setWindow(SWIGTYPE_p_SDL_Window value) {
    sdl2javaJNI.SDL_MessageBoxData_window_set(swigCPtr, this, SWIGTYPE_p_SDL_Window.getCPtr(value));
  }

  public SWIGTYPE_p_SDL_Window getWindow() {
    long cPtr = sdl2javaJNI.SDL_MessageBoxData_window_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_SDL_Window(cPtr, false);
  }

  public void setTitle(String value) {
    sdl2javaJNI.SDL_MessageBoxData_title_set(swigCPtr, this, value);
  }

  public String getTitle() {
    return sdl2javaJNI.SDL_MessageBoxData_title_get(swigCPtr, this);
  }

  public void setMessage(String value) {
    sdl2javaJNI.SDL_MessageBoxData_message_set(swigCPtr, this, value);
  }

  public String getMessage() {
    return sdl2javaJNI.SDL_MessageBoxData_message_get(swigCPtr, this);
  }

  public void setNumbuttons(int value) {
    sdl2javaJNI.SDL_MessageBoxData_numbuttons_set(swigCPtr, this, value);
  }

  public int getNumbuttons() {
    return sdl2javaJNI.SDL_MessageBoxData_numbuttons_get(swigCPtr, this);
  }

  public void setButtons(SDL_MessageBoxButtonData value) {
    sdl2javaJNI.SDL_MessageBoxData_buttons_set(swigCPtr, this, SDL_MessageBoxButtonData.getCPtr(value), value);
  }

  public SDL_MessageBoxButtonData getButtons() {
    long cPtr = sdl2javaJNI.SDL_MessageBoxData_buttons_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SDL_MessageBoxButtonData(cPtr, false);
  }

  public void setColorScheme(SDL_MessageBoxColorScheme value) {
    sdl2javaJNI.SDL_MessageBoxData_colorScheme_set(swigCPtr, this, SDL_MessageBoxColorScheme.getCPtr(value), value);
  }

  public SDL_MessageBoxColorScheme getColorScheme() {
    long cPtr = sdl2javaJNI.SDL_MessageBoxData_colorScheme_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SDL_MessageBoxColorScheme(cPtr, false);
  }

  public SDL_MessageBoxData() {
    this(sdl2javaJNI.new_SDL_MessageBoxData(), true);
  }

}
