/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.libsdl2;

public final class SDL_DisplayOrientation {
  public final static SDL_DisplayOrientation SDL_ORIENTATION_UNKNOWN = new SDL_DisplayOrientation("SDL_ORIENTATION_UNKNOWN");
  public final static SDL_DisplayOrientation SDL_ORIENTATION_LANDSCAPE = new SDL_DisplayOrientation("SDL_ORIENTATION_LANDSCAPE");
  public final static SDL_DisplayOrientation SDL_ORIENTATION_LANDSCAPE_FLIPPED = new SDL_DisplayOrientation("SDL_ORIENTATION_LANDSCAPE_FLIPPED");
  public final static SDL_DisplayOrientation SDL_ORIENTATION_PORTRAIT = new SDL_DisplayOrientation("SDL_ORIENTATION_PORTRAIT");
  public final static SDL_DisplayOrientation SDL_ORIENTATION_PORTRAIT_FLIPPED = new SDL_DisplayOrientation("SDL_ORIENTATION_PORTRAIT_FLIPPED");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SDL_DisplayOrientation swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + SDL_DisplayOrientation.class + " with value " + swigValue);
  }

  private SDL_DisplayOrientation(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SDL_DisplayOrientation(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SDL_DisplayOrientation(String swigName, SDL_DisplayOrientation swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SDL_DisplayOrientation[] swigValues = { SDL_ORIENTATION_UNKNOWN, SDL_ORIENTATION_LANDSCAPE, SDL_ORIENTATION_LANDSCAPE_FLIPPED, SDL_ORIENTATION_PORTRAIT, SDL_ORIENTATION_PORTRAIT_FLIPPED };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

