/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.libsdl2;

public class SDL_FPoint {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SDL_FPoint(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SDL_FPoint obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(SDL_FPoint obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        sdl2javaJNI.delete_SDL_FPoint(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setX(float value) {
    sdl2javaJNI.SDL_FPoint_x_set(swigCPtr, this, value);
  }

  public float getX() {
    return sdl2javaJNI.SDL_FPoint_x_get(swigCPtr, this);
  }

  public void setY(float value) {
    sdl2javaJNI.SDL_FPoint_y_set(swigCPtr, this, value);
  }

  public float getY() {
    return sdl2javaJNI.SDL_FPoint_y_get(swigCPtr, this);
  }

  public SDL_FPoint() {
    this(sdl2javaJNI.new_SDL_FPoint(), true);
  }

}
