/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.libsdl2;

public class SDL_AssertData {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SDL_AssertData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SDL_AssertData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(SDL_AssertData obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        sdl2javaJNI.delete_SDL_AssertData(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setAlways_ignore(int value) {
    sdl2javaJNI.SDL_AssertData_always_ignore_set(swigCPtr, this, value);
  }

  public int getAlways_ignore() {
    return sdl2javaJNI.SDL_AssertData_always_ignore_get(swigCPtr, this);
  }

  public void setTrigger_count(long value) {
    sdl2javaJNI.SDL_AssertData_trigger_count_set(swigCPtr, this, value);
  }

  public long getTrigger_count() {
    return sdl2javaJNI.SDL_AssertData_trigger_count_get(swigCPtr, this);
  }

  public void setCondition(String value) {
    sdl2javaJNI.SDL_AssertData_condition_set(swigCPtr, this, value);
  }

  public String getCondition() {
    return sdl2javaJNI.SDL_AssertData_condition_get(swigCPtr, this);
  }

  public void setFilename(String value) {
    sdl2javaJNI.SDL_AssertData_filename_set(swigCPtr, this, value);
  }

  public String getFilename() {
    return sdl2javaJNI.SDL_AssertData_filename_get(swigCPtr, this);
  }

  public void setLinenum(int value) {
    sdl2javaJNI.SDL_AssertData_linenum_set(swigCPtr, this, value);
  }

  public int getLinenum() {
    return sdl2javaJNI.SDL_AssertData_linenum_get(swigCPtr, this);
  }

  public void setFunction(String value) {
    sdl2javaJNI.SDL_AssertData_function_set(swigCPtr, this, value);
  }

  public String getFunction() {
    return sdl2javaJNI.SDL_AssertData_function_get(swigCPtr, this);
  }

  public void setNext(SDL_AssertData value) {
    sdl2javaJNI.SDL_AssertData_next_set(swigCPtr, this, SDL_AssertData.getCPtr(value), value);
  }

  public SDL_AssertData getNext() {
    long cPtr = sdl2javaJNI.SDL_AssertData_next_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SDL_AssertData(cPtr, false);
  }

  public SDL_AssertData() {
    this(sdl2javaJNI.new_SDL_AssertData(), true);
  }

}
