/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.libsdl2;

public final class SDL_DisplayEventID {
  public final static SDL_DisplayEventID SDL_DISPLAYEVENT_NONE = new SDL_DisplayEventID("SDL_DISPLAYEVENT_NONE");
  public final static SDL_DisplayEventID SDL_DISPLAYEVENT_ORIENTATION = new SDL_DisplayEventID("SDL_DISPLAYEVENT_ORIENTATION");
  public final static SDL_DisplayEventID SDL_DISPLAYEVENT_CONNECTED = new SDL_DisplayEventID("SDL_DISPLAYEVENT_CONNECTED");
  public final static SDL_DisplayEventID SDL_DISPLAYEVENT_DISCONNECTED = new SDL_DisplayEventID("SDL_DISPLAYEVENT_DISCONNECTED");
  public final static SDL_DisplayEventID SDL_DISPLAYEVENT_MOVED = new SDL_DisplayEventID("SDL_DISPLAYEVENT_MOVED");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SDL_DisplayEventID swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + SDL_DisplayEventID.class + " with value " + swigValue);
  }

  private SDL_DisplayEventID(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SDL_DisplayEventID(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SDL_DisplayEventID(String swigName, SDL_DisplayEventID swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SDL_DisplayEventID[] swigValues = { SDL_DISPLAYEVENT_NONE, SDL_DISPLAYEVENT_ORIENTATION, SDL_DISPLAYEVENT_CONNECTED, SDL_DISPLAYEVENT_DISCONNECTED, SDL_DISPLAYEVENT_MOVED };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

