/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.libsdl2;

public class SDL_ControllerAxisEvent {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SDL_ControllerAxisEvent(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SDL_ControllerAxisEvent obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(SDL_ControllerAxisEvent obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        sdl2javaJNI.delete_SDL_ControllerAxisEvent(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setType(SWIGTYPE_p_uint32_t value) {
    sdl2javaJNI.SDL_ControllerAxisEvent_type_set(swigCPtr, this, SWIGTYPE_p_uint32_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint32_t getType() {
    return new SWIGTYPE_p_uint32_t(sdl2javaJNI.SDL_ControllerAxisEvent_type_get(swigCPtr, this), true);
  }

  public void setTimestamp(SWIGTYPE_p_uint32_t value) {
    sdl2javaJNI.SDL_ControllerAxisEvent_timestamp_set(swigCPtr, this, SWIGTYPE_p_uint32_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint32_t getTimestamp() {
    return new SWIGTYPE_p_uint32_t(sdl2javaJNI.SDL_ControllerAxisEvent_timestamp_get(swigCPtr, this), true);
  }

  public void setWhich(SWIGTYPE_p_int32_t value) {
    sdl2javaJNI.SDL_ControllerAxisEvent_which_set(swigCPtr, this, SWIGTYPE_p_int32_t.getCPtr(value));
  }

  public SWIGTYPE_p_int32_t getWhich() {
    return new SWIGTYPE_p_int32_t(sdl2javaJNI.SDL_ControllerAxisEvent_which_get(swigCPtr, this), true);
  }

  public void setAxis(SWIGTYPE_p_uint8_t value) {
    sdl2javaJNI.SDL_ControllerAxisEvent_axis_set(swigCPtr, this, SWIGTYPE_p_uint8_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint8_t getAxis() {
    return new SWIGTYPE_p_uint8_t(sdl2javaJNI.SDL_ControllerAxisEvent_axis_get(swigCPtr, this), true);
  }

  public void setPadding1(SWIGTYPE_p_uint8_t value) {
    sdl2javaJNI.SDL_ControllerAxisEvent_padding1_set(swigCPtr, this, SWIGTYPE_p_uint8_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint8_t getPadding1() {
    return new SWIGTYPE_p_uint8_t(sdl2javaJNI.SDL_ControllerAxisEvent_padding1_get(swigCPtr, this), true);
  }

  public void setPadding2(SWIGTYPE_p_uint8_t value) {
    sdl2javaJNI.SDL_ControllerAxisEvent_padding2_set(swigCPtr, this, SWIGTYPE_p_uint8_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint8_t getPadding2() {
    return new SWIGTYPE_p_uint8_t(sdl2javaJNI.SDL_ControllerAxisEvent_padding2_get(swigCPtr, this), true);
  }

  public void setPadding3(SWIGTYPE_p_uint8_t value) {
    sdl2javaJNI.SDL_ControllerAxisEvent_padding3_set(swigCPtr, this, SWIGTYPE_p_uint8_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint8_t getPadding3() {
    return new SWIGTYPE_p_uint8_t(sdl2javaJNI.SDL_ControllerAxisEvent_padding3_get(swigCPtr, this), true);
  }

  public void setValue(SWIGTYPE_p_int16_t value) {
    sdl2javaJNI.SDL_ControllerAxisEvent_value_set(swigCPtr, this, SWIGTYPE_p_int16_t.getCPtr(value));
  }

  public SWIGTYPE_p_int16_t getValue() {
    return new SWIGTYPE_p_int16_t(sdl2javaJNI.SDL_ControllerAxisEvent_value_get(swigCPtr, this), true);
  }

  public void setPadding4(SWIGTYPE_p_uint16_t value) {
    sdl2javaJNI.SDL_ControllerAxisEvent_padding4_set(swigCPtr, this, SWIGTYPE_p_uint16_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint16_t getPadding4() {
    return new SWIGTYPE_p_uint16_t(sdl2javaJNI.SDL_ControllerAxisEvent_padding4_get(swigCPtr, this), true);
  }

  public SDL_ControllerAxisEvent() {
    this(sdl2javaJNI.new_SDL_ControllerAxisEvent(), true);
  }

}
