/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.libsdl2;

public final class SDL_WindowFlags {
  public final static SDL_WindowFlags SDL_WINDOW_FULLSCREEN = new SDL_WindowFlags("SDL_WINDOW_FULLSCREEN", sdl2javaJNI.SDL_WINDOW_FULLSCREEN_get());
  public final static SDL_WindowFlags SDL_WINDOW_OPENGL = new SDL_WindowFlags("SDL_WINDOW_OPENGL", sdl2javaJNI.SDL_WINDOW_OPENGL_get());
  public final static SDL_WindowFlags SDL_WINDOW_SHOWN = new SDL_WindowFlags("SDL_WINDOW_SHOWN", sdl2javaJNI.SDL_WINDOW_SHOWN_get());
  public final static SDL_WindowFlags SDL_WINDOW_HIDDEN = new SDL_WindowFlags("SDL_WINDOW_HIDDEN", sdl2javaJNI.SDL_WINDOW_HIDDEN_get());
  public final static SDL_WindowFlags SDL_WINDOW_BORDERLESS = new SDL_WindowFlags("SDL_WINDOW_BORDERLESS", sdl2javaJNI.SDL_WINDOW_BORDERLESS_get());
  public final static SDL_WindowFlags SDL_WINDOW_RESIZABLE = new SDL_WindowFlags("SDL_WINDOW_RESIZABLE", sdl2javaJNI.SDL_WINDOW_RESIZABLE_get());
  public final static SDL_WindowFlags SDL_WINDOW_MINIMIZED = new SDL_WindowFlags("SDL_WINDOW_MINIMIZED", sdl2javaJNI.SDL_WINDOW_MINIMIZED_get());
  public final static SDL_WindowFlags SDL_WINDOW_MAXIMIZED = new SDL_WindowFlags("SDL_WINDOW_MAXIMIZED", sdl2javaJNI.SDL_WINDOW_MAXIMIZED_get());
  public final static SDL_WindowFlags SDL_WINDOW_MOUSE_GRABBED = new SDL_WindowFlags("SDL_WINDOW_MOUSE_GRABBED", sdl2javaJNI.SDL_WINDOW_MOUSE_GRABBED_get());
  public final static SDL_WindowFlags SDL_WINDOW_INPUT_FOCUS = new SDL_WindowFlags("SDL_WINDOW_INPUT_FOCUS", sdl2javaJNI.SDL_WINDOW_INPUT_FOCUS_get());
  public final static SDL_WindowFlags SDL_WINDOW_MOUSE_FOCUS = new SDL_WindowFlags("SDL_WINDOW_MOUSE_FOCUS", sdl2javaJNI.SDL_WINDOW_MOUSE_FOCUS_get());
  public final static SDL_WindowFlags SDL_WINDOW_FULLSCREEN_DESKTOP = new SDL_WindowFlags("SDL_WINDOW_FULLSCREEN_DESKTOP", sdl2javaJNI.SDL_WINDOW_FULLSCREEN_DESKTOP_get());
  public final static SDL_WindowFlags SDL_WINDOW_FOREIGN = new SDL_WindowFlags("SDL_WINDOW_FOREIGN", sdl2javaJNI.SDL_WINDOW_FOREIGN_get());
  public final static SDL_WindowFlags SDL_WINDOW_ALLOW_HIGHDPI = new SDL_WindowFlags("SDL_WINDOW_ALLOW_HIGHDPI", sdl2javaJNI.SDL_WINDOW_ALLOW_HIGHDPI_get());
  public final static SDL_WindowFlags SDL_WINDOW_MOUSE_CAPTURE = new SDL_WindowFlags("SDL_WINDOW_MOUSE_CAPTURE", sdl2javaJNI.SDL_WINDOW_MOUSE_CAPTURE_get());
  public final static SDL_WindowFlags SDL_WINDOW_ALWAYS_ON_TOP = new SDL_WindowFlags("SDL_WINDOW_ALWAYS_ON_TOP", sdl2javaJNI.SDL_WINDOW_ALWAYS_ON_TOP_get());
  public final static SDL_WindowFlags SDL_WINDOW_SKIP_TASKBAR = new SDL_WindowFlags("SDL_WINDOW_SKIP_TASKBAR", sdl2javaJNI.SDL_WINDOW_SKIP_TASKBAR_get());
  public final static SDL_WindowFlags SDL_WINDOW_UTILITY = new SDL_WindowFlags("SDL_WINDOW_UTILITY", sdl2javaJNI.SDL_WINDOW_UTILITY_get());
  public final static SDL_WindowFlags SDL_WINDOW_TOOLTIP = new SDL_WindowFlags("SDL_WINDOW_TOOLTIP", sdl2javaJNI.SDL_WINDOW_TOOLTIP_get());
  public final static SDL_WindowFlags SDL_WINDOW_POPUP_MENU = new SDL_WindowFlags("SDL_WINDOW_POPUP_MENU", sdl2javaJNI.SDL_WINDOW_POPUP_MENU_get());
  public final static SDL_WindowFlags SDL_WINDOW_KEYBOARD_GRABBED = new SDL_WindowFlags("SDL_WINDOW_KEYBOARD_GRABBED", sdl2javaJNI.SDL_WINDOW_KEYBOARD_GRABBED_get());
  public final static SDL_WindowFlags SDL_WINDOW_VULKAN = new SDL_WindowFlags("SDL_WINDOW_VULKAN", sdl2javaJNI.SDL_WINDOW_VULKAN_get());
  public final static SDL_WindowFlags SDL_WINDOW_METAL = new SDL_WindowFlags("SDL_WINDOW_METAL", sdl2javaJNI.SDL_WINDOW_METAL_get());
  public final static SDL_WindowFlags SDL_WINDOW_INPUT_GRABBED = new SDL_WindowFlags("SDL_WINDOW_INPUT_GRABBED", sdl2javaJNI.SDL_WINDOW_INPUT_GRABBED_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SDL_WindowFlags swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + SDL_WindowFlags.class + " with value " + swigValue);
  }

  private SDL_WindowFlags(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SDL_WindowFlags(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SDL_WindowFlags(String swigName, SDL_WindowFlags swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SDL_WindowFlags[] swigValues = { SDL_WINDOW_FULLSCREEN, SDL_WINDOW_OPENGL, SDL_WINDOW_SHOWN, SDL_WINDOW_HIDDEN, SDL_WINDOW_BORDERLESS, SDL_WINDOW_RESIZABLE, SDL_WINDOW_MINIMIZED, SDL_WINDOW_MAXIMIZED, SDL_WINDOW_MOUSE_GRABBED, SDL_WINDOW_INPUT_FOCUS, SDL_WINDOW_MOUSE_FOCUS, SDL_WINDOW_FULLSCREEN_DESKTOP, SDL_WINDOW_FOREIGN, SDL_WINDOW_ALLOW_HIGHDPI, SDL_WINDOW_MOUSE_CAPTURE, SDL_WINDOW_ALWAYS_ON_TOP, SDL_WINDOW_SKIP_TASKBAR, SDL_WINDOW_UTILITY, SDL_WINDOW_TOOLTIP, SDL_WINDOW_POPUP_MENU, SDL_WINDOW_KEYBOARD_GRABBED, SDL_WINDOW_VULKAN, SDL_WINDOW_METAL, SDL_WINDOW_INPUT_GRABBED };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

