/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.libsdl2;

public class SDL_RWops_hidden {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SDL_RWops_hidden(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SDL_RWops_hidden obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(SDL_RWops_hidden obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        sdl2javaJNI.delete_SDL_RWops_hidden(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SDL_RWops_hidden_mem getMem() {
    long cPtr = sdl2javaJNI.SDL_RWops_hidden_mem_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SDL_RWops_hidden_mem(cPtr, false);
  }

  public SDL_RWops_hidden_unknown getUnknown() {
    long cPtr = sdl2javaJNI.SDL_RWops_hidden_unknown_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SDL_RWops_hidden_unknown(cPtr, false);
  }

  public SDL_RWops_hidden() {
    this(sdl2javaJNI.new_SDL_RWops_hidden(), true);
  }

}
