/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.libsdl2;

public class SDL_ControllerTouchpadEvent {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SDL_ControllerTouchpadEvent(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SDL_ControllerTouchpadEvent obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(SDL_ControllerTouchpadEvent obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        sdl2javaJNI.delete_SDL_ControllerTouchpadEvent(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setType(SWIGTYPE_p_uint32_t value) {
    sdl2javaJNI.SDL_ControllerTouchpadEvent_type_set(swigCPtr, this, SWIGTYPE_p_uint32_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint32_t getType() {
    return new SWIGTYPE_p_uint32_t(sdl2javaJNI.SDL_ControllerTouchpadEvent_type_get(swigCPtr, this), true);
  }

  public void setTimestamp(SWIGTYPE_p_uint32_t value) {
    sdl2javaJNI.SDL_ControllerTouchpadEvent_timestamp_set(swigCPtr, this, SWIGTYPE_p_uint32_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint32_t getTimestamp() {
    return new SWIGTYPE_p_uint32_t(sdl2javaJNI.SDL_ControllerTouchpadEvent_timestamp_get(swigCPtr, this), true);
  }

  public void setWhich(SWIGTYPE_p_int32_t value) {
    sdl2javaJNI.SDL_ControllerTouchpadEvent_which_set(swigCPtr, this, SWIGTYPE_p_int32_t.getCPtr(value));
  }

  public SWIGTYPE_p_int32_t getWhich() {
    return new SWIGTYPE_p_int32_t(sdl2javaJNI.SDL_ControllerTouchpadEvent_which_get(swigCPtr, this), true);
  }

  public void setTouchpad(SWIGTYPE_p_int32_t value) {
    sdl2javaJNI.SDL_ControllerTouchpadEvent_touchpad_set(swigCPtr, this, SWIGTYPE_p_int32_t.getCPtr(value));
  }

  public SWIGTYPE_p_int32_t getTouchpad() {
    return new SWIGTYPE_p_int32_t(sdl2javaJNI.SDL_ControllerTouchpadEvent_touchpad_get(swigCPtr, this), true);
  }

  public void setFinger(SWIGTYPE_p_int32_t value) {
    sdl2javaJNI.SDL_ControllerTouchpadEvent_finger_set(swigCPtr, this, SWIGTYPE_p_int32_t.getCPtr(value));
  }

  public SWIGTYPE_p_int32_t getFinger() {
    return new SWIGTYPE_p_int32_t(sdl2javaJNI.SDL_ControllerTouchpadEvent_finger_get(swigCPtr, this), true);
  }

  public void setX(float value) {
    sdl2javaJNI.SDL_ControllerTouchpadEvent_x_set(swigCPtr, this, value);
  }

  public float getX() {
    return sdl2javaJNI.SDL_ControllerTouchpadEvent_x_get(swigCPtr, this);
  }

  public void setY(float value) {
    sdl2javaJNI.SDL_ControllerTouchpadEvent_y_set(swigCPtr, this, value);
  }

  public float getY() {
    return sdl2javaJNI.SDL_ControllerTouchpadEvent_y_get(swigCPtr, this);
  }

  public void setPressure(float value) {
    sdl2javaJNI.SDL_ControllerTouchpadEvent_pressure_set(swigCPtr, this, value);
  }

  public float getPressure() {
    return sdl2javaJNI.SDL_ControllerTouchpadEvent_pressure_get(swigCPtr, this);
  }

  public SDL_ControllerTouchpadEvent() {
    this(sdl2javaJNI.new_SDL_ControllerTouchpadEvent(), true);
  }

}
