/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.libsdl2;

public class SDL_MouseWheelEvent {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SDL_MouseWheelEvent(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SDL_MouseWheelEvent obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(SDL_MouseWheelEvent obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        sdl2javaJNI.delete_SDL_MouseWheelEvent(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setType(SWIGTYPE_p_uint32_t value) {
    sdl2javaJNI.SDL_MouseWheelEvent_type_set(swigCPtr, this, SWIGTYPE_p_uint32_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint32_t getType() {
    return new SWIGTYPE_p_uint32_t(sdl2javaJNI.SDL_MouseWheelEvent_type_get(swigCPtr, this), true);
  }

  public void setTimestamp(SWIGTYPE_p_uint32_t value) {
    sdl2javaJNI.SDL_MouseWheelEvent_timestamp_set(swigCPtr, this, SWIGTYPE_p_uint32_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint32_t getTimestamp() {
    return new SWIGTYPE_p_uint32_t(sdl2javaJNI.SDL_MouseWheelEvent_timestamp_get(swigCPtr, this), true);
  }

  public void setWindowID(SWIGTYPE_p_uint32_t value) {
    sdl2javaJNI.SDL_MouseWheelEvent_windowID_set(swigCPtr, this, SWIGTYPE_p_uint32_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint32_t getWindowID() {
    return new SWIGTYPE_p_uint32_t(sdl2javaJNI.SDL_MouseWheelEvent_windowID_get(swigCPtr, this), true);
  }

  public void setWhich(SWIGTYPE_p_uint32_t value) {
    sdl2javaJNI.SDL_MouseWheelEvent_which_set(swigCPtr, this, SWIGTYPE_p_uint32_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint32_t getWhich() {
    return new SWIGTYPE_p_uint32_t(sdl2javaJNI.SDL_MouseWheelEvent_which_get(swigCPtr, this), true);
  }

  public void setX(SWIGTYPE_p_int32_t value) {
    sdl2javaJNI.SDL_MouseWheelEvent_x_set(swigCPtr, this, SWIGTYPE_p_int32_t.getCPtr(value));
  }

  public SWIGTYPE_p_int32_t getX() {
    return new SWIGTYPE_p_int32_t(sdl2javaJNI.SDL_MouseWheelEvent_x_get(swigCPtr, this), true);
  }

  public void setY(SWIGTYPE_p_int32_t value) {
    sdl2javaJNI.SDL_MouseWheelEvent_y_set(swigCPtr, this, SWIGTYPE_p_int32_t.getCPtr(value));
  }

  public SWIGTYPE_p_int32_t getY() {
    return new SWIGTYPE_p_int32_t(sdl2javaJNI.SDL_MouseWheelEvent_y_get(swigCPtr, this), true);
  }

  public void setDirection(SWIGTYPE_p_uint32_t value) {
    sdl2javaJNI.SDL_MouseWheelEvent_direction_set(swigCPtr, this, SWIGTYPE_p_uint32_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint32_t getDirection() {
    return new SWIGTYPE_p_uint32_t(sdl2javaJNI.SDL_MouseWheelEvent_direction_get(swigCPtr, this), true);
  }

  public void setPreciseX(float value) {
    sdl2javaJNI.SDL_MouseWheelEvent_preciseX_set(swigCPtr, this, value);
  }

  public float getPreciseX() {
    return sdl2javaJNI.SDL_MouseWheelEvent_preciseX_get(swigCPtr, this);
  }

  public void setPreciseY(float value) {
    sdl2javaJNI.SDL_MouseWheelEvent_preciseY_set(swigCPtr, this, value);
  }

  public float getPreciseY() {
    return sdl2javaJNI.SDL_MouseWheelEvent_preciseY_get(swigCPtr, this);
  }

  public void setMouseX(SWIGTYPE_p_int32_t value) {
    sdl2javaJNI.SDL_MouseWheelEvent_mouseX_set(swigCPtr, this, SWIGTYPE_p_int32_t.getCPtr(value));
  }

  public SWIGTYPE_p_int32_t getMouseX() {
    return new SWIGTYPE_p_int32_t(sdl2javaJNI.SDL_MouseWheelEvent_mouseX_get(swigCPtr, this), true);
  }

  public void setMouseY(SWIGTYPE_p_int32_t value) {
    sdl2javaJNI.SDL_MouseWheelEvent_mouseY_set(swigCPtr, this, SWIGTYPE_p_int32_t.getCPtr(value));
  }

  public SWIGTYPE_p_int32_t getMouseY() {
    return new SWIGTYPE_p_int32_t(sdl2javaJNI.SDL_MouseWheelEvent_mouseY_get(swigCPtr, this), true);
  }

  public SDL_MouseWheelEvent() {
    this(sdl2javaJNI.new_SDL_MouseWheelEvent(), true);
  }

}
