/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.libsdl2;

public final class SDL_YUV_CONVERSION_MODE {
  public final static SDL_YUV_CONVERSION_MODE SDL_YUV_CONVERSION_JPEG = new SDL_YUV_CONVERSION_MODE("SDL_YUV_CONVERSION_JPEG");
  public final static SDL_YUV_CONVERSION_MODE SDL_YUV_CONVERSION_BT601 = new SDL_YUV_CONVERSION_MODE("SDL_YUV_CONVERSION_BT601");
  public final static SDL_YUV_CONVERSION_MODE SDL_YUV_CONVERSION_BT709 = new SDL_YUV_CONVERSION_MODE("SDL_YUV_CONVERSION_BT709");
  public final static SDL_YUV_CONVERSION_MODE SDL_YUV_CONVERSION_AUTOMATIC = new SDL_YUV_CONVERSION_MODE("SDL_YUV_CONVERSION_AUTOMATIC");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SDL_YUV_CONVERSION_MODE swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + SDL_YUV_CONVERSION_MODE.class + " with value " + swigValue);
  }

  private SDL_YUV_CONVERSION_MODE(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SDL_YUV_CONVERSION_MODE(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SDL_YUV_CONVERSION_MODE(String swigName, SDL_YUV_CONVERSION_MODE swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SDL_YUV_CONVERSION_MODE[] swigValues = { SDL_YUV_CONVERSION_JPEG, SDL_YUV_CONVERSION_BT601, SDL_YUV_CONVERSION_BT709, SDL_YUV_CONVERSION_AUTOMATIC };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

