/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.libsdl2;

public class SDL_RWops {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SDL_RWops(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SDL_RWops obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(SDL_RWops obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        sdl2javaJNI.delete_SDL_RWops(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSize(SWIGTYPE_p_f_p_struct_SDL_RWops__int64_t value) {
    sdl2javaJNI.SDL_RWops_size_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_SDL_RWops__int64_t.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_SDL_RWops__int64_t getSize() {
    long cPtr = sdl2javaJNI.SDL_RWops_size_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_SDL_RWops__int64_t(cPtr, false);
  }

  public void setSeek(SWIGTYPE_p_f_p_struct_SDL_RWops_int64_t_int__int64_t value) {
    sdl2javaJNI.SDL_RWops_seek_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_SDL_RWops_int64_t_int__int64_t.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_SDL_RWops_int64_t_int__int64_t getSeek() {
    long cPtr = sdl2javaJNI.SDL_RWops_seek_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_SDL_RWops_int64_t_int__int64_t(cPtr, false);
  }

  public void setRead(SWIGTYPE_p_f_p_struct_SDL_RWops_p_void_size_t_size_t__size_t value) {
    sdl2javaJNI.SDL_RWops_read_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_SDL_RWops_p_void_size_t_size_t__size_t.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_SDL_RWops_p_void_size_t_size_t__size_t getRead() {
    long cPtr = sdl2javaJNI.SDL_RWops_read_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_SDL_RWops_p_void_size_t_size_t__size_t(cPtr, false);
  }

  public void setWrite(SWIGTYPE_p_f_p_struct_SDL_RWops_p_q_const__void_size_t_size_t__size_t value) {
    sdl2javaJNI.SDL_RWops_write_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_SDL_RWops_p_q_const__void_size_t_size_t__size_t.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_SDL_RWops_p_q_const__void_size_t_size_t__size_t getWrite() {
    long cPtr = sdl2javaJNI.SDL_RWops_write_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_SDL_RWops_p_q_const__void_size_t_size_t__size_t(cPtr, false);
  }

  public void setClose(SWIGTYPE_p_f_p_struct_SDL_RWops__int value) {
    sdl2javaJNI.SDL_RWops_close_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_SDL_RWops__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_SDL_RWops__int getClose() {
    long cPtr = sdl2javaJNI.SDL_RWops_close_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_SDL_RWops__int(cPtr, false);
  }

  public void setType(SWIGTYPE_p_uint32_t value) {
    sdl2javaJNI.SDL_RWops_type_set(swigCPtr, this, SWIGTYPE_p_uint32_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint32_t getType() {
    return new SWIGTYPE_p_uint32_t(sdl2javaJNI.SDL_RWops_type_get(swigCPtr, this), true);
  }

  public SDL_RWops_hidden getHidden() {
    long cPtr = sdl2javaJNI.SDL_RWops_hidden_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SDL_RWops_hidden(cPtr, false);
  }

  public SDL_RWops() {
    this(sdl2javaJNI.new_SDL_RWops(), true);
  }

}
