/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.libsdl2;

public final class SDL_AssertState {
  public final static SDL_AssertState SDL_ASSERTION_RETRY = new SDL_AssertState("SDL_ASSERTION_RETRY");
  public final static SDL_AssertState SDL_ASSERTION_BREAK = new SDL_AssertState("SDL_ASSERTION_BREAK");
  public final static SDL_AssertState SDL_ASSERTION_ABORT = new SDL_AssertState("SDL_ASSERTION_ABORT");
  public final static SDL_AssertState SDL_ASSERTION_IGNORE = new SDL_AssertState("SDL_ASSERTION_IGNORE");
  public final static SDL_AssertState SDL_ASSERTION_ALWAYS_IGNORE = new SDL_AssertState("SDL_ASSERTION_ALWAYS_IGNORE");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SDL_AssertState swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + SDL_AssertState.class + " with value " + swigValue);
  }

  private SDL_AssertState(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SDL_AssertState(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SDL_AssertState(String swigName, SDL_AssertState swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SDL_AssertState[] swigValues = { SDL_ASSERTION_RETRY, SDL_ASSERTION_BREAK, SDL_ASSERTION_ABORT, SDL_ASSERTION_IGNORE, SDL_ASSERTION_ALWAYS_IGNORE };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

