/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.libsdl2;

public class SWIGTYPE_p_f_p_struct_SDL_Window_p_q_const__struct_SDL_Point_p_void__SDL_HitTestResult {
  private transient long swigCPtr;

  protected SWIGTYPE_p_f_p_struct_SDL_Window_p_q_const__struct_SDL_Point_p_void__SDL_HitTestResult(long cPtr, @SuppressWarnings("unused") boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_f_p_struct_SDL_Window_p_q_const__struct_SDL_Point_p_void__SDL_HitTestResult() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_f_p_struct_SDL_Window_p_q_const__struct_SDL_Point_p_void__SDL_HitTestResult obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(SWIGTYPE_p_f_p_struct_SDL_Window_p_q_const__struct_SDL_Point_p_void__SDL_HitTestResult obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

